{{- if .Values.h2ogpt.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "h2ogpt.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "h2ogpt.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.h2ogpt.overrideConfig }}
  {{ printf "H2OGPT_%s" $key | upper }}: {{ $value | quote }}
{{- end }}
{{- end }}
---
{{- if .Values.tgi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "h2ogpt.fullname" . }}-tgi-inference-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "h2ogpt.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.tgi.overrideConfig }}
  {{ printf "%s" $key | upper }}: {{ $value | quote }}
{{- end }}
{{- end }}
---
{{- if .Values.vllm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "h2ogpt.fullname" . }}-vllm-inference-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "h2ogpt.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.vllm.overrideConfig }}
  {{ printf "%s" $key | upper }}: {{ $value | quote }}
{{- end }}
{{- end }}
