{{- if .Values.vllm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "h2ogpt.fullname" . }}-vllm-inference-config
  namespace: {{ include "h2ogpt.namespace" . | quote }}
  labels:
    {{- include "h2ogpt.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.vllm.overrideConfig }}
  {{ printf "%s" $key | upper }}: {{ $value | quote }}
{{- end }}
{{- end }}
