---
{{- if and (.Values.vllm.enabled) (not .Values.vllm.storage.useEphemeral) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "h2ogpt.fullname" . }}-vllm-inference-volume
  namespace: {{ include "h2ogpt.namespace" . | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: {{ .Values.vllm.storage.class | quote }}
  storageClassName: {{ .Values.vllm.storage.class }}
  resources:
    requests:
      storage: {{ .Values.vllm.storage.size | quote }}
{{- end }}
